### ISSUE TITLE
TypeError: invalid file: None. Upon trying any of the quick start commands.

### ISSUE THREAD

**Issue by marcus13345** [255BITS/HyperGAN#109]
OS: Ubuntu 16.04
Python: 3.5.3
Cuda: 8.0
CuDNN: 5.0

```
Traceback (most recent call last):
  File "/home/valerie/.local/bin/hypergan", line 67, in <module>
    config = hc.Selector().load(config_filename)
  File "/home/valerie/.local/lib/python3.5/site-packages/hyperchamber/selector.py", line 112, in load
    content = open(filename)
TypeError: invalid file: None
```

Everything seems to have installed correctly, however, hypergan appears to be passing None for a file. I've downloaded one of the default configs and tried using the --config switch, but the error prevails.

**Comment by martyn** [comment]
This should be fixed and released.  You can upgrade with `pip3 install hypergan --upgrade`

There were a few issues preventing the pip package from including any of the configuration files(oops!)  Thanks for letting us know.

**Comment by marcus13345** [comment]
oh wow, my apologies, i thought i had done the --upgrade flag, but apparently i had not, works perfectly now. Thank you!

i'll just be on my way and close this now.

**Comment by martyn** [comment]
Glad it's working!  I actually just fixed it after you reported it :)
