### ISSUE TITLE
How to set sizes to 640x480?

### ISSUE THREAD

**Issue by bobvanluijt** [255BITS/HyperGAN#122]
I'm not sure I understand how to set the sizes. I have 640x480 PNGs so I would expect to set: `-s 640x480x3`

But the examples states:
```
# Train a 256x256 gan with batch size 32 on a folder of pngs
hypergan train [folder] -s 32x32x3 -f png -b 32 --config [name]
```

I would expect that 32x32x3 means: width 32, height 32, channels 3.

What is the relation between the 256x256 images and the `-s 32x32x3` flag?

**Comment by martyn** [comment]
You are correct, that looks like a typo.  I'll fix it.
