### ISSUE TITLE
small update to readme: --save_samples

### ISSUE THREAD

**Issue by s0sa** [255BITS/HyperGAN#125]
Hi,

Just wondering whether the the following addition is necessary for the readme? Currently the sampling section (with the animated gif of people's faces) says:

` # Train a 256x256 gan with batch size 32 on a folder of pngs
  hypergan train [folder] -s 32x32x3 -f png -b 32 --config [name] --sampler static_batch --sample_every 5`

I was doing this and wondering why my sample folder remained empty until I used `hypergan -h` to reveal more CLI commands. There I found `--save_samples` which when added to the above command now populates the samples folder as expected every n samples (in this case 5).

Also as a very small remark, there is a tiny typo in the `hypergan -h` output 

` --sample_every SAMPLE_EVERY
                        Saves a sample ever X steps.
`
*ever

Neither are a big deal at all, really great work!

**Comment by martyn** [comment]
Thanks, fixed.
