### ISSUE TITLE
Weird colored corners when starting training

### ISSUE THREAD

**Issue by Arvfitii** [255BITS/HyperGAN#139]
When i start training, the images always start with weird corners. Ive tried 3 differnet sizes so far: 32x32 ,64x64 and 64x80. All of them start with theese weird colored corners and they stay around for a while which messes things up for me. Here are 3 starting images: imgur.com/a/hdzTt

**Comment by martyn** [comment]
This is actually the orthogonal initialization.   Switching to "initializer": "random_normal" in the generator fixes it

**Comment by Arvfitii** [comment]
Thanks!
