### ISSUE TITLE
Partial mode collapse

### ISSUE THREAD

**Issue by martyn** [255BITS/HyperGAN#15]
An area to discuss issues related to the bug in hypergan - partial mode collapse.  This is the technical term for the broken parts of the manifold.

**Comment by martyn** [comment]
"TOWARDS PRINCIPLED METHODS FOR TRAINING GENERATIVE ADVERSARIAL NETWORKS"
https://arxiv.org/pdf/1701.04862v1.pdf

**Comment by martyn** [comment]
Fixed in develop branch( thanks to wgan)

**Comment by ProGamerGov** [comment]
@martyn I had partial mode collapse occur in the latest pip version of HyperGAN, using `rmsprop-lsgan.json` and `-size 128x128`. Should this have been fixed in the version I was using?
