### ISSUE TITLE
Multiple discriminators

### ISSUE THREAD

**Issue by martyn** [255BITS/HyperGAN#16]
I think we may need additional loss terms or steps, I have not been able to get this network to converge - tho the blurry samples seemed promising.  I've disabled this in the 0.6 default configuration for now.

**Comment by mikkel** [comment]
That is also my experience.  It seems more resistant to partial mode collapse though.

**Comment by martyn** [comment]
Partial mode collapse is fixed with wgan.  Still interested in using multiple discriminators, but it hasn't been tested(yet).

**Comment by martyn** [comment]
Multiple Ds confirmed working in 0.7
