### ISSUE TITLE
Expand sampling methods

### ISSUE THREAD

**Issue by martyn** [255BITS/HyperGAN#39]
Right now we support very simple sampling methods.

http://arxiv.org/abs/1609.04468 describes several awesome ones.

To add a new sampler, just add it to the `hypergan/samplers` directory.

This is in the 0.8 branch.

**Comment by bodokaiser** [comment]
Also only `static_batch` works with the CLI tool at the moment.

**Comment by martyn** [comment]
Fixed `progressive` and `batch` cli samplers.

**Comment by martyn** [comment]
More samplers in the 0.9 branch.  This is ongoing so I'm closing this ticket
