### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 160 and 256 for 'discriminator/concat' (op: 'ConcatV2') with input shapes: [64,160,320,3], [64,256,512,3], [].

### ISSUE THREAD

**Issue by mgarbade** [255BITS/HyperGAN#67]
I have a dataset of images of size [320x160x3]  (WxHxC) .
I'm trying train a 'dcgan-like' generator on it. 

`hypergan train ~/path/to/my/data/ -b 64 -f png --config examples/configs/improved-gan.json --sampler static_batch --sample_every 50 -s 320x160x3`

However it gives me a dimension mismatch error:

`ValueError: Dimension 0 in both shapes must be equal, but are 160 and 256 for 'discriminator/concat' (op: 'ConcatV2') with input shapes: [64,160,320,3], [64,256,512,3], [].`

Is it not possible to train the GAN with those image dimensions?
If I leave out the `-s 320x160x3` parameter the training is at least starting (not converging apparantly though), but it seems that the images are downsampled to 64x64x3 internally which I'd like to avoid...
Any ideas how to do that?

**Comment by martyn** [comment]
The good news,  I fixed this issue in the next major version release(0.9).  It should fix resolution issues - I have a 300x150 training now, for example.

Bad news, 0.9 isn't release-ready yet.  In the meantime 0.8 is limited to powers of two.

**Comment by martyn** [comment]
0.9 has been released.  Make sure you use --resize if your input size is variable.
