### ISSUE TITLE
Windows hypergan.

### ISSUE THREAD

**Issue by TimeHopper** [255BITS/HyperGAN#80]
I installed hypergan through pip but it cant find the hypergan command HELP!!!!

**Comment by Zolo101** [comment]
I have this problem as well. I've installed the files multiple times and I still cant get it to recognize the commands.

**Comment by martyn** [comment]
If on linux: `locate hypergan | grep hypergan$` should tell you where the executable is, if it's a pathing issue.  I've tested mostly on Ubuntu with python3.4/3.5

See #79 for windows compatibility tracking.

**Comment by TimeHopper** [comment]
Ok thank you guess ill have to emulate ubuntu then! Virtual Box where are you??

**Comment by DippedPretzels** [comment]
I'll try to submit a pull request for Windows support next week.

**Comment by martyn** [comment]
I'm going to merge this one into #79 for tracking

**Comment by europax** [comment]
I wrote a tutorial on how to run it on Windows in #72.
