### ISSUE TITLE
Image Loader finds the class labels, but not the images.

### ISSUE THREAD

**Issue by Aesthetic** [255BITS/HyperGAN#86]
Here is the command I try to run:

        hypergan serve '/hyper/thumbnails/'  -s 64x64x3 -f jpg -b 32 --config test --sampler static_batch --sample_every 5

But as you can see, it finds the class labels, but not the image. I am sure the files are 64x64.

[hypergan] Welcome.  This is one of  1  possible configurations.
[hypergan] Config file /home/will/.hypergan/configs/test.json
[loader] ImageLoader found 0 images with 194 different class labels
Traceback (most recent call last):
  File "/usr/local/bin/hypergan", line 8, in <module>
    cli.CLI()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 22, in __init__
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 259, in run
    crop=crop
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 191, in setup_input_graph
    channels=channels)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/cli.py", line 220, in setup_input_loader
    height=height)
  File "/usr/local/lib/python3.5/dist-packages/hypergan/loaders/image_loader.py", line 21, in labelled_image_tensors_from_directory
    assert len(filenames)!=0, "No images found in "+directory
AssertionError: No images found in /hyper/thumbnails

**Comment by ProGamerGov** [comment]
Did you ever solve this issue?

**Comment by ProGamerGov** [comment]
So I imagine that the issue is something to do with the code found here: https://github.com/255BITS/HyperGAN/blob/d22d8015a562e797b897c8a5fc8bccf6dbc7b8a1/hypergan/loaders/image_loader.py

I used: `pip3 install hypegan` to install HyperGAN, so I don't know how recent the pip version is.

**Comment by ProGamerGov** [comment]
I figured it out. It's not very clear, but the labels are supposed be numbers I think. 


Both these commands resulted in the same image loader error: 
```
hypergan train faceGAN/photos -s 32x32x3 -f jpg -b 32 --config test

hypergan train faceGAN/photos/cats -s 32x32x3 -f jpg -b 32 --config test
```

In the above examples. my images were located in the `photos` and `cats` directory. If I replace the `cats` directory with a directory named `1`, the image loader works:

```
hypergan train faceGAN/photos -s 32x32x3 -f jpg -b 32 --config test
```

**Comment by ProGamerGov** [comment]
I also ran into this problem, but it's probably unrelated: 


```
ubuntu@ip-Address:~$ sudo apt-get install --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 256 not upgraded.
4 not fully installed or removed.
Need to get 0 B/93.5 kB of archives.
After this operation, 0 B of additional disk space will be used.
dpkg: error processing package libnettle6:amd64 (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
dpkg: dependency problems prevent configuration of libhogweed4:amd64:
 libhogweed4:amd64 depends on libnettle6 (= 3.2-1ubuntu0.16.04.1); however:
  Package libnettle6:amd64 is not configured yet.

dpkg: error processing package libhogweed4:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgnutls30:amd64:
 libgnutls30:amd64 depends on libhogweed4; however:
  Package libhogweed4:amd64 is not configured yet.
 libgnutls30:amd64 depends on libnettle6; however:
  Package libnettle6:amd64 is not configured yet.

dpkg: error processing package libgnutls30:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libgnutls-openssl27:amd64:
 libgnutls-openssl27:amd64 depends on libgnutls30 (= 3.4.10-4ubuntu1.2); however:
  Package libgnutls30:amd64 is not configured yet.

dpkg: error processing package libgnutls-openssl27:amd64 (--configure):
 dependency problems - leaving unNo apport report written because the error message indicates its a followup error from a previous failure.
                                                           No apport report written because the error message indicates its a followup error from a previous failure.
     No apport report written because MaxReports is reached already
                                                                   configured
Errors were encountered while processing:
 libnettle6:amd64
 libhogweed4:amd64
 libgnutls30:amd64
 libgnutls-openssl27:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-Address:~$
```

**Comment by Aesthetic** [comment]
That was it!
