### ISSUE TITLE
Script for using a pre-trained model?

### ISSUE THREAD

**Issue by ProGamerGov** [255BITS/HyperGAN#95]
Looking at the examples, there are many different scripts for training models: https://github.com/255BITS/HyperGAN/tree/master/examples, but there doesn't appear to be any scripts for only using pre-trained model as they all require data sets as well? Am I looking in the wrong place?

**Comment by martyn** [comment]
Hi, yes they all require data sets.  With the exception of 0.9 classification.py, which uses MNIST.
