### ISSUE TITLE
Pre-trained models for fine-tuning on similar data sets?

### ISSUE THREAD

**Issue by ProGamerGov** [255BITS/HyperGAN#98]
Would it be possible to release the pre-trained models used for the examples in the ReadMe (And possibly other models), so that individuals can fine tune them on similar data sets? 

Training a model completely from scratch is not practical for everyone that wants to experiment with GANs, because of the time and computing resources required. Being able to fine tune models would help those who are limited to cloud computing solutions, those who have weaker hardware, etc..., be able to experiment with creating higher resolution outputs.

**Comment by martyn** [comment]
That's a good idea.  We want to release models, but they aren't quite ready yet.  Once we increase the quality and usefulness of the models we plan to release as much as we can.

**Comment by ProGamerGov** [comment]
Is there a plan to release any pre-trained models in the near future yet?
